#!/bin/bash

BATCH_SIZE=128
VIS_INT=500
LOG_INT=50
DATASET_DIR=./dataset
MODEL=resnet

export CUDA_VISIBLE_DEVICES=0

# RGB + SPEED
./runs_train/run1.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

# RGB + SPEED + DISP
#./runs_train/run2.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

# RGB + SPEED + DISP + FLOW
#./runs_train/run3.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

## RGB + STACKED
#./runs_train/run4.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

## RGB + STACKED + DISP
#./runs_train/run5.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

## RGB + STACKED + DISP + FLOW
#./runs_train/run6.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL
