#!/bin/bash

BATCH_SIZE=32
VIS_INT=500
LOG_INT=50
DATASET_DIR=dataset
MODEL=nvidia


# RGB + SPEED
./runs_test/run1.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

# RGB + SPEED + DISP
./runs_test/run2.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

# RGB + SPEED + DISP + FLOW
./runs_test/run3.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

# RGB + STACKED
./runs_test/run4.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

# RGB + STACKED + DISP 
./runs_test/run5.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL

# RGB + STACKED + DISP + FLOW
./runs_test/run6.sh $BATCH_SIZE $VIS_INT $LOG_INT $DATASET_DIR $MODEL


